### ISSUE TITLE
First digits?

### ISSUE THREAD

**Issue by gentlemenVap** [qopu/discord-image-brute#1]
What do you mean by first digits? Can you elaborate please? Thank you :)

**Comment by qopu** [comment]
Usually, the first 3-5 digits of the "Message ID" are identical **for different messages in the same chat.**

For example, these two images were sent in the same chat:
https://cdn.discordapp.com/attachments/940308931484467230/1057286924789878874/image.png
https://cdn.discordapp.com/attachments/940308931484467230/1057286939742580806/image.png

![image](https://i.imgur.com/S2jpw7u.png)
![image](https://i.imgur.com/bavsHud.png)

Not sure why, but I have a clue that it's an image hash value in the DB.

**Comment by gentlemenVap** [comment]
Thank you for the clarification.
